### ISSUE TITLE
How to compile the C code and output

### ISSUE THREAD

**Issue by iprada** [pk7zuva/Circle_finder#1]
Dear developers of Circle_finder,

I am Iñigo Prada-Luengo, the developer behind Circle-Map (https://github.com/iprada/Circle-Map). I am trying to compare Circle-Map with Circle_finder, however the code exits with the common `Segmentation fault (Core dumped)` error found on C/C++ programs.  In order to be able to execute the pipeline, can you provide information about how to compile the C code of the package?

Furthermore, I don't see any information about the format and the name of the output files generated by Circle_finder. Could you please provide a minimal example of the output, and the name of the output file generated by your software?

Best wishes,

Iñigo

**Comment by pk7zuva** [comment]
Hi Iñigo,

Sorry for late reply. Somehow I could not get your message.

I suggest you re-compile all the "C" program. This should fix the problem. 

Please let me know if this solves your problem.

Best,

Pankaj
