### ISSUE TITLE
Multiple fastq files

### ISSUE THREAD

**Issue by Brawni** [pk7zuva/Circle_finder#3]
Hello,

Thanks for sharing this pipeline! I am all set up but I'm not sure how to go forward on this as I see from the example that only two fastq files need to be specified whereas in my 10x scATAC fastq file folder there are three pairs of fastq files. Is it ok to run the pipeline on one pair at the time or there is a way to specify all the fastq at once?

Thanks a lot!

**Comment by pk7zuva** [comment]
Hi,
Thank you for your interest in Circle_finder. One can use Circle_finder scATACseq data if the read-length is >75. 
The current version of Circle_finder does not support eccDNA identification in ATAC-seq data with read-length less than 75.
Pankaj
