### ISSUE TITLE
Error for test with Circle-finder

### ISSUE THREAD

**Issue by assane-mbodj** [pk7zuva/Circle_finder#4]
Hello, I am new to programming and I found your article on ATAC-seq. And I wanted to test it on my plant data to detect circles.
But after installing circle-finder I tried to do the test with hg38 data but it displays this error message.

assane@gwas:~/Circle_finder$ bash scripts/microDNA.InOne.sh /media/assane/DD-2To/fastq_file/Index11_1.fq /media/assane/DD-2To/fastq_file/Index11_2.fq 24 C4-2 49 10000 /home/assane/Circle_finder/output/
[main_samview] fail to read the header from "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.sam".
[E::hts_open_format] Failed to open file "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.bam" : No such file or directory
samtools sort: can't open "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.bam": No such file or directory
[E::hts_open_format] Failed to open file "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.sorted.bam" : No such file or directory
samtools index: failed to open "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.sorted.bam": No such file or directory
rm: impossible de supprimer '/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.bam': Aucun fichier ou dossier de ce type
[E::hts_open_format] Failed to open file "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.sorted.bam" : No such file or directory
samtools view: failed to open "/media/assane/DD-2To/fastq_file/Index11_2.fq.hg38.sorted.bam" for reading: No such file or directory
bash: FromBamExtractProperpairreads2Island2Inetrsect2MappedUnmapped4human.sh: Aucun fichier ou dossier de ce type
bash: microDNA.RunAsOneJob.sh: Aucun fichier ou dossier de ce type
rm: impossible de supprimer 'microDNA.JT.postalign.TeMp1.bed': Aucun fichier ou dossier de ce type
awk: fatal : impossible d'ouvrir le fichier « junction.microDNA » en lecture (Aucun fichier ou dossier de ce type)
awk: ligne de commande:2: $2>1000 && $2<195471971 && $3<195471971 && $3>$2 && ($3-$2)<=
awk: ligne de commande:2:                                                              ^ fin de chaîne ou passage à la ligne inattendu
*****ERROR: Unrecognized parameter: microDNA.prealign.up501.bed *****

Tool:    bedtools getfasta (aka fastaFromBed)
Version: v2.27.1
Summary: Extract DNA sequences from a fasta file based on feature coordinates.

Can I have your help please
Thanks in advance

**Comment by pk7zuva** [comment]
Hi assane-mbodj,
Sorry for the late reply. 
Two things here. 
1. You need to make a new genome index file (your organism of interest)
2. If your library was not prepared from the circular DNA enriched then please use script "https://github.com/pk7zuva/Circle_finder/blob/master/circle_finder-pipeline-bwa-mem-samblaster.sh". 
Hope this helps.
Pankaj
