### ISSUE TITLE
code typo

### ISSUE THREAD

**Issue by jinyung** [pk7zuva/Circle_finder#5]
Hi Pankaj,

In [line 72](https://github.com/pk7zuva/Circle_finder/blob/0d9ffc2dfc0ef573eebb5935f3c4fffabc9dcc89/circle_finder-pipeline-bwa-mem-samblaster.sh#L72) of `circle_finder-pipeline-bwa-mem-samblaster.sh`, 
```
awk '$1==$11 && $1==$21 && $7==$17 && length(8)<=12 && length($18)<=12 && length($28)<=12'
```
I think `length(8)` should be `length($8)` . Also, I'm curious about the reason to filter the length of CIGAR string here, what does it do?

JY

**Comment by yangmqglobe** [comment]
Curious, too.

And, the pipeline output so many result, and most of them seems to be mapping error to me, the false positive rate is to high.

**Comment by pk7zuva** [comment]
Hi  Jinyung,
Yes, you are right. Thanks. This is corrected now.
